name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - name: Step 1 - Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ github.ref_name }} # dynamically use branch name
        - name: Configure Git user
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

        - name: Step 3 - Set up Maven Central Repository
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            #server-id: central
            #server-username: MAVEN_USERNAME
            #server-password: MAVEN_PASSWORD
            #gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
            #gpg-passphrase: MAVEN_GPG_PASSPHRASE

      # Step 5: Use the Maven release plugin to prepare and perform the release
        - name: Step 5 - Perform Maven Release
          run: |
            mvn -B release:prepare
          #run: |
          #  mvn -B release:prepare release:perform -DpushChanges=false      
          env:
            #MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
            #MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
            #MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              